#define MyAppVersion "3.1.0.4+4"
; Script generated by the Inno Script Studio Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
WizardImageFile=compiler:WizClassicImage.bmp
;WizardImageFile=customInnoSetupImage.bmp
AppName=PyMOL-Open-Source
AppVersion={#MyAppVersion}
AppCopyright=Hannah Kullik, Schrodinger LLC
AppId={{192F52C3-D86D-4735-9929-C7DF593CB534}
DefaultDirName={userappdata}\PyMOL-Open-Source
AppPublisher=Hannah Kullik
VersionInfoProductName=PyMOL-Open-Source
MinVersion=10.0.19045
OutputDir=..\..\dist
OutputBaseFilename=PyMOL-Open-Source_v{#MyAppVersion}_x64_setup
; VersionInfoCopyright=GNU GPL-3.0
DisableDirPage=True
DisableProgramGroupPage=True
DisableReadyPage=True
ArchitecturesInstallIn64BitMode=x64os
WizardStyle=modern
UninstallDisplayName=PyMOL-Open-Source
UninstallDisplayIcon={app}\assets\logo.ico
LicenseFile=LICENSE.txt
; This is necessary if the setup will exceed 2 GB
DiskSpanning=no
PrivilegesRequired=none

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Dirs]
Name: "{app}"
Name: "{app}\assets"
Name: "{app}\bin"

[Files]
Source: "..\..\..\inno-build-release\inno-assets\logo.ico"; DestDir: "{app}\assets"; Flags: ignoreversion recursesubdirs createallsubdirs;
Source: "..\..\..\inno-build-release\inno-sources\*"; DestDir: "{app}\bin"; Flags: ignoreversion recursesubdirs createallsubdirs;

[Icons]
Name: "{commondesktop}\Open-Source PyMOL"; Filename: "{app}\bin\launch_pymol.cmd"; IconFilename: "{app}\assets\logo.ico"
Name: "{commonstartmenu}\Open-Source PyMOL"; Filename: "{app}\bin\launch_pymol.cmd"; IconFilename: "{app}\assets\logo.ico"

[UninstallDelete]
Type: filesandordirs; Name: "{app}"
