#A* -------------------------------------------------------------------
#B* This file contains source code for running a GitHub automation
#-* related to the build process of the PyMOL computer program
#C* Copyright 2025 by Martin Urban.
#D* -------------------------------------------------------------------
#E* It is unlawful to modify or remove this copyright notice.
#F* -------------------------------------------------------------------
#G* Please see the accompanying LICENSE file for further information.
#H* -------------------------------------------------------------------
#I* Additional authors of this source file include:
#-*
#-*
#-*
#Z* -------------------------------------------------------------------
name: Build app packages

on: [push]

jobs:
  # ----- Windows build section
  build-windows:
    strategy:
      fail-fast: false
      matrix:
        win_arch: ['x86', 'x64']
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Create virtual environment
        run: |
          python -m venv .venv
          call .venv\Scripts\activate.bat
          python -m pip install --upgrade setuptools pip build 
          python -m pip install -r requirements.txt
        shell: cmd

      - name: Download Inno Setup installer
        run: |
          Invoke-WebRequest -Uri https://files.jrsoftware.org/is/6/innosetup-6.4.2.exe -OutFile inno-setup.exe

      - name: Install Inno Setup
        run: |
          .\inno-setup.exe /SILENT

      - name: Add Inno Setup to PATH
        run: |
          $env:PATH += ";C:\Program Files (x86)\Inno Setup 6"

      - name: Build frozen Python application
        run: |
          .\win_automator.bat build app
          .\win_automator.bat build inno_setup_ci

        shell: powershell

      - name: Compile .iss file
        run: |
          iscc os_specific/windows/inno_setup/setup.iss

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Open-Source-PyMOL-Windows-${{ matrix.win_arch }}-Setup
          path: ./dist/*.exe
  # --- end

  # ----- macOS build section
  build-macos:
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-13, macos-14 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Create virtual environment
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install wheel setuptools 
          python -m pip install -r requirements.txt

      - name: Build app package
        run: |
          ./automator.sh build app

      - name: Rename app package
        run: mv dist/open_source_pymol-3.1.0a0.app dist/Open-Source-PyMOL-3.1.0a0.app

      - name: Build DMG
        uses: urban233/create-dmg-actions@v0.0.2
        with:
          dmg_name: 'Open-Source-PyMOL'
          src_dir: 'dist/Open-Source-PyMOL-3.1.0a0.app'
          bg_filepath: 'os_specific/macos/dmg_bg.png'

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Open-Source-PyMOL-macOS-${{ matrix.arch }}-Setup
          path: ./*.dmg
  # --- end

  # ----- GNU Linux build section
  build-gnu-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Create virtual environment
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install wheel setuptools 
          python -m pip install -r requirements.txt

      - name: Build app package
        run: |
          ./automator.sh build app

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Open-Source-PyMOL-GNU-Linux-x86_64-Setup
          path: ./dist/exe.linux*
  # --- end
